pipelines:
  secret-ops:
    group: platform
    label_template: "${git[:8]}"
    materials:
      git:
        git: "git@git.ai-traders.com:platform/secret-ops.git"
        branch: master
        blacklist:
          - "doc/**/*"
          - "**/*.md"
    stages:
      - first_stage:
          clean_workspace: true
          jobs:
            first_job:
              resources:
                - docker
                - small
              tasks:
               - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - "echo \"running custom first stage\" && cat README.md"
