format_version: 3
pipelines:
  secret-ops:
    group: platform
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    secure_variables:
      VAULT_TOKEN: "AES:+e5Gl62gTddtxRlVDyqr2w==:btuabrO+3UyGrG3TcjXcIotcPbOq3yDqFFPPSJFfCYc="
    stages:
      - test:
          clean_workspace: true
          jobs:
            bash:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_bash
            python:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_python
      - release:
          clean_workspace: true
          jobs:
            code:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks release
      - publish:
          clean_workspace: true
          jobs:
            github:
              resources:
                - docker
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks publish
