format_version: 3
pipelines:
  secret-ops:
    group: platform
    label_template: "${git[:8]}"
    materials:
      git:
        type: configrepo
    stages:
      - test:
          clean_workspace: true
          secure_variables:
            VAULT_TOKEN: "AES:cfOqIgg44MdPN15Nj5T1pg==:hME/TpUAo6d2E9DjQI/iEjQzf2i0+Cswp5YCZX6Oz3YA1gVGwzTh1vDRM22StcQV"
          jobs:
            bash:
              elastic_profile_id: w.c1.m1024.e5
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_bash
            python:
              elastic_profile_id: w.c1.m1024.e5
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks test_python
      - release:
          clean_workspace: true
          jobs:
            code:
              elastic_profile_id: w.c1.m1024.e5
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks release
      - publish:
          clean_workspace: true
          jobs:
            swift:
              elastic_profile_id: w.c1.m1024.e5
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks publish
