#!/bin/bash

# Copyright 2019 Ewa Czechowska, Tomasz Sętkowski
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

secret_ops::program_name() {
  echo "SECRET-OPS"
}
secret_ops::log_debug() {
  if [ "${RELEASER_LOG_LEVEL}" == "debug" ]; then
    echo -e "$(date "+%d-%m-%Y %T") $(secret_ops::program_name) debug: ${1}" >&2
  fi
}
secret_ops::log_info() {
  echo -e "$(date "+%d-%m-%Y %T") $(secret_ops::program_name) info: ${1}" >&2
}
secret_ops::log_error() {
  echo -e "\e[31m$(date "+%d-%m-%Y %T") $(secret_ops::program_name) error: $1\e[0m" >&2
  echo -e "\e[31m$(date "+%d-%m-%Y %T") $(secret_ops::program_name) error: File: ${BASH_SOURCE[0]}\e[0m" >&2
  echo -e "\e[31m$(date "+%d-%m-%Y %T") $(secret_ops::program_name) error: Line numbers: ${BASH_LINENO[*]}\e[0m" >&2
}
secret_ops::log_warn() {
  echo -e "\e[33m$(date "+%d-%m-%Y %T") $(secret_ops::program_name) warn: $1\e[0m" >&2
}

export VAULT_ADDR="${VAULT_ADDR:-https://vault.kudulab.io:8200}"

function secret_ops::encrypt_with_gocd_common {
  local variable_to_encrypt=${1?variable_to_encrypt not set}
  local gocd_url=${2?gocd_url not set}
  local credentials=${3?credentials not set}

  echo "Encrypting with gocd server: ${gocd_url}" >&2
  #FIXME: curl to go server is insecure because go uses self-signed certs
  local HTTP_RESPONSE=$(curl --silent --write-out "HTTPSTATUS:%{http_code}" \
    "https://${gocd_url}:8154/go/api/admin/encrypt" --insecure ${credentials} \
    -H 'Accept: application/vnd.go.cd.v1+json' \
    -H 'Content-Type: application/json' \
    -X POST -d "{ \"value\" : \"${variable_to_encrypt}\" }")
  # extract the status
  local HTTP_STATUS=$(echo $HTTP_RESPONSE | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')
  if [ ! $HTTP_STATUS -eq 200  ]; then
    echo "Error encrypting token for gocd [HTTP status: $HTTP_STATUS]" >&2
    exit 1
  fi
  local HTTP_BODY=$(echo $HTTP_RESPONSE | sed -e 's/HTTPSTATUS\:.*//g')
  echo $HTTP_BODY | jq '.encrypted_value'
}
# Encrypts any string, uses GoCD server.
function secret_ops::encrypt_with_gocd_top {
  local variable_to_encrypt=${1?variable_to_encrypt not set}
  local user=${2:-}
  url_dir=$user
  if [ -z ${user} ]; then
    user="$(whoami)"
    url_dir=$user
    if [[ "${url_dir}" == "go" ]]; then
      url_dir="gocd"
    fi
  fi
  if [ -z ${url_dir} ]; then
    echo "Unknown user name"
    exit 5
  fi
  local my_gocd_pass
  my_gocd_pass=$(vault read -field=value secret/${url_dir}/gocd_password)
  if [[ $? != "0" ]]; then exit 1; fi

  secret_ops::encrypt_with_gocd_common "${variable_to_encrypt}" "go2-production.kudulab.io" "-u ${user}:${my_gocd_pass}"
}
function secret_ops::encrypt_with_gocd_base {
  local variable_to_encrypt=${1?variable_to_encrypt not set}
  secret_ops::encrypt_with_gocd_common "${variable_to_encrypt}" "go2.ai-traders.com" ""
}

# Encrypts Vault Token.
function secret_ops::generate_certs_token_gocd_top {
  local vault_token=$(vault token create -policy=issue-ait-certs -field token)
  local secured_token_gocd=$(secret_ops::encrypt_with_gocd_top "${vault_token}")
  echo "Generated token and secured for gocd" >&2
  echo "${secured_token_gocd}"
}
function secret_ops::generate_certs_token2 {
  secret_ops::generate_certs_token_gocd_top
}

function secret_ops::insert_vault_token_gocd_yaml {
  local secured_token_gocd=${1?secured_token_gocd not set}

  echo "Replacing pipeline config with VAULT_TOKEN: ${secured_token_gocd}"
  find . -name '*.gocd.yaml' -exec sed -i -E "s#VAULT_TOKEN\:.*#VAULT_TOKEN: ${secured_token_gocd}#g" {} \;
}
function secret_ops::insert_vault_token_gocd_yaml2 {
  secret_ops::insert_vault_token_gocd_yaml  $1
}

function secret_ops::docker_login {
  vault_user_path="$(whoami)"
  if [ $vault_user_path == "go" ]; then
    vault_user_path="gocd"
  fi
  dockerhub_user=$(vault read -field=user secret/$vault_user_path/dockerhub)
  vault read -field=password secret/$vault_user_path/dockerhub | docker login --username $dockerhub_user --password-stdin
}
